// defaultSettings:
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const TOGGLE_BACKGROUND_IMAGE = 'TOGGLE_BACKGROUND_IMAGE';
export const TOGGLE_GRID_OVERLAY = 'TOGGLE_GRID_OVERLAY';
export const TOGGLE_CORRECT_PLACEMENT = 'TOGGLE_CORRECT_PLACEMENT';

// uiState:
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB';